<?php

return [
	'document' => [
		'columns' => 32,
		'type'=> [
			0 => 'integer',
			1 => 'string',
			2 => 'string',
			3 => 'string',
			4 => 'string',
			5 => 'string',
			6 => 'string',
			7 => 'double',
			8 => 'double',
			9 => 'integer',
			10 => 'string',
			11 => 'integer',
			12 => 'string',
			13 => 'integer',
			14 => 'string',
			15 => 'integer',
			16 => 'integer',
			17 => 'string', //fecha
			18 => 'integer',
			19 => 'string', //fecha
			20 => 'integer',
			21 => 'string',
			22 => 'string',
			23 => 'integer',
			24 => 'string',
			25 => 'string',
			26 => 'string',
			27 => 'integer',
			28 => 'integer',
			29 => 'integer',
			30 => 'integer',
			31 => 'integer',
		],
		'heads' => [
			'company',
			'cRut',
			'cCCost',
			'cName',
			'cDir',
			'cCommune',
			'cPhone',
			'cX',
			'cY',
			'movil',
			'plate',
			'codDriver',
			'namDriver',
			'codAux',
			'namAux',
			'guideNumber',
			'orderNumber',
			'guideDate',
			'routeNumber',
			'routeDate',
			'codSalesMan',
			'namSalesMan',
			'email',
			'codCarriage',
			'compCarriage',
			'codItem',
			'desItem',
			'cantItem',
			'itemLine',
			'orderBulk',
			'rowOrder',
			'cRegion',
		],
		'model' => 'App\Models\Stock',
		'update' => function($values){
			return [
				'where'  => ['code' => utf8_encode(trim($values['code']))],
				'values' => ['quantity' => utf8_encode(trim($values['quantity']))],
			];
		}
	],
	'crossdocking' => [
		'columns' => 32,
		'type'=> [
			0 => 'integer',
			1 => 'string',
			2 => 'string',
			3 => 'string',
			4 => 'string',
			5 => 'string',
			6 => 'string',
			7 => 'string',
			8 => 'string',
			9 => 'integer',
			10 => 'string',
			11 => 'integer',
			12 => 'string',
			13 => 'integer',
			14 => 'string',
			15 => 'integer',
			16 => 'integer',
			17 => 'string', //fecha
			18 => 'integer',
			19 => 'string', //fecha
			20 => 'string',
			21 => 'string',
			22 => 'string',
			23 => 'integer',
			24 => 'string',
			25 => 'string',
			26 => 'string',
			27 => 'string',
			28 => 'string',
			29 => 'string',
			30 => 'string',
			31 => 'string',
		],
		'heads' => [
			'company',
			'cRut',
			'cCCost',
			'cName',
			'cDir',
			'cCommune',
			'cPhone',
			'cX',
			'cY',
			'movil',
			'plate',
			'codDriver',
			'namDriver',
			'codAux',
			'namAux',
			'guideNumber',
			'orderNumber',
			'guideDate',
			'routeNumber',
			'routeDate',
			'codSalesMan',
			'namSalesMan',
			'email',
			'codCarriage',
			'compCarriage',
			'codItem',
			'desItem',
			'cantItem',
			'itemLine',
			'orderBulk',
			'rowOrder',
			'cRegion',
		],
	],
];